# **1. Normalization Problem**

In [28]:
# import numpy to access its library
import numpy as np

# store the value of a random 5x5 ndarray in X
X = np.random.rand(5, 5)
# store the mean of X in variable A
A = X.mean()
# store the standard deviation of X in B
B = X.std()
# store the normalization formula in C
C = (X - A) / B

# prints the 5x5 array with original Values
print("The Original Values Generated are:")
print(X)

# prints the 5x5 array with the normalized values
print("The Normalized Values are:")
print(C)

The Original Values Generated are:
[[0.13814155 0.89629086 0.92245677 0.93330008 0.79406436]
 [0.58759801 0.96949339 0.06955327 0.08950852 0.96830453]
 [0.46407505 0.68784998 0.63574641 0.73787025 0.46774163]
 [0.93646382 0.30028383 0.21545066 0.92237397 0.25825055]
 [0.54785126 0.43886868 0.42406502 0.31341392 0.64881748]]
The Normalized Values are:
[[-1.49500272  1.10121463  1.19081754  1.22794951  0.75114872]
 [ 0.04412239  1.3518904  -1.72987744 -1.66154238  1.34781925]
 [-0.3788714   0.38742668  0.20900248  0.55871681 -0.3663155 ]
 [ 1.23878349 -0.93976039 -1.23026433  1.19053399 -1.08369977]
 [-0.09198693 -0.46518845 -0.51588233 -0.89479752  0.25376323]]


# **2. Divisible By 3 Problem**

In [34]:
# import numpy to access its library
import numpy as np

# generates values inside an array ranging from 1-100 
X = np.arange(1, 101)
# square the values inside the array and declare it as A 
A = X * X
# Reshape array A into a 10X10 Matrix
B = A.reshape(10, 10)

# checks and filters the value divisible by 3 in A 
# returns an array filled with the numbers that are divisible by 3
C = A[A % 3 == 0]
# reshape the array into a 3X11 for readability 
D = C.reshape(3, 11)

# print the squares of the first 100 natural numbers
print("The squares of the first 100 natural numbers are:")
print(B)

# \n for readability 
print("\n") 

# prints the numbers divisible by 3 found on array B 
print("The numbers divisible by 3 are:")
print(D)

The squares of the first 100 natural numbers are:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


The numbers divisible by 3 are:
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
